# Generated by Django 2.2.1 on 2019-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190520_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Password',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Title',
            field=models.CharField(max_length=20),
        ),
    ]
