# Generated by Django 2.2.1 on 2019-05-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsTubeChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('rank', models.SmallIntegerField(unique=True)),
            ],
        ),
    ]
